[package]
name = "mini-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.8", features = ["image_rs"] }
image = "0.24.5"
lazy_static = "1.4.0"
